/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/datasets/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Dataset Endpoint */
        post: operations["validate_dataset_endpoint_datasets_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planning-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Planning Runs
         * @description Archive of every persisted run, newest first.
         */
        get: operations["list_planning_runs_planning_runs_get"];
        put?: never;
        /** Create Planning Run */
        post: operations["create_planning_run_planning_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planning-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Planning Run */
        get: operations["get_planning_run_planning_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planning-runs/{run_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_planning_runs__run_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planning-runs/{run_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export */
        get: operations["export_planning_runs__run_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planning-runs/{run_id}/lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lock Schedule Item */
        post: operations["lock_schedule_item_planning_runs__run_id__lock_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/planning-runs/{run_id}/replan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replan */
        post: operations["replan_planning_runs__run_id__replan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/railradar/trains/{train_number}/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_railradar_trains__train_number__live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/railradar/trains/{train_number}/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Route */
        get: operations["route_railradar_trains__train_number__route_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/railradar/trains/{train_number}/timetable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Timetable */
        get: operations["timetable_railradar_trains__train_number__timetable_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rapidblock-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Rapidblock Request */
        post: operations["create_rapidblock_request_rapidblock_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rapidblock-requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rapidblock Request */
        get: operations["get_rapidblock_request_rapidblock_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AiEstimate */
        AiEstimate: {
            /** Duration Max Minutes */
            duration_max_minutes: number;
            /** Duration Min Minutes */
            duration_min_minutes: number;
            /** Duration Minutes */
            duration_minutes: number;
            /** Job Id */
            job_id: string;
            /** Priority */
            priority: number;
            /** Reason Codes */
            reason_codes: string[];
            /**
             * Source
             * @enum {string}
             */
            source: "LOCAL_HEURISTIC" | "DETERMINISTIC_FALLBACK";
        };
        /** ApprovalRequest */
        ApprovalRequest: {
            /** Comment */
            comment: string;
            /** Reviewer */
            reviewer: string;
        };
        /** ApprovalResponse */
        ApprovalResponse: {
            approval: components["schemas"]["ApprovalSummary"];
            /** Approved */
            approved: boolean;
            /** Run Id */
            run_id: string;
        };
        /** ApprovalSummary */
        ApprovalSummary: {
            /**
             * Approved At
             * Format: date-time
             */
            approved_at: string;
            /** Comment */
            comment: string;
            /** Reviewer */
            reviewer: string;
            /** Ruleset Version */
            ruleset_version: string;
            /** Run Id */
            run_id: string;
            /** Snapshot Id */
            snapshot_id: string;
        };
        /** DatasetCounts */
        DatasetCounts: {
            /**
             * Assets
             * @default 0
             */
            assets: number;
            /**
             * Jobs
             * @default 0
             */
            jobs: number;
            /**
             * Resources
             * @default 0
             */
            resources: number;
            /**
             * Sections
             * @default 0
             */
            sections: number;
            /**
             * Windows
             * @default 0
             */
            windows: number;
        };
        /** DatasetValidationResponse */
        DatasetValidationResponse: {
            counts: components["schemas"]["DatasetCounts"];
            /** Errors */
            errors: components["schemas"]["ValidationIssue"][];
            /** Snapshot Candidate Id */
            snapshot_candidate_id: string | null;
            /** Valid */
            valid: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Job */
        Job: {
            /** Allowed Windows */
            allowed_windows: string[];
            /** Asset Id */
            asset_id: string;
            /**
             * Department
             * @enum {string}
             */
            department: "TRACK" | "SIGNAL" | "ELECTRICAL" | "CIVIL";
            /** Duration Max Minutes */
            duration_max_minutes: number;
            /** Duration Min Minutes */
            duration_min_minutes: number;
            /** Duration Minutes */
            duration_minutes: number;
            /** Job Id */
            job_id: string;
            /** Priority */
            priority: number;
            /** Required Resources */
            required_resources: string[];
            /** Section Id */
            section_id: string;
            status: components["schemas"]["JobStatus"];
            /** Work Type */
            work_type: string;
        };
        /** JobContext */
        JobContext: {
            /** Allowed Windows */
            allowed_windows: string[];
            /** Asset Id */
            asset_id: string;
            /** Department */
            department: string;
            /** Duration Minutes */
            duration_minutes: number;
            /** Job Id */
            job_id: string;
            /** Priority */
            priority: number;
            /** Required Resources */
            required_resources: string[];
            /** Section Id */
            section_id: string;
            /** Work Type */
            work_type: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "UNSCHEDULED" | "SCHEDULED" | "LOCKED" | "REJECTED" | "INVALID";
        /** KpiSummary */
        KpiSummary: {
            /** Baseline Asset Downtime Minutes */
            baseline_asset_downtime_minutes: number;
            /** Baseline Closure Minutes */
            baseline_closure_minutes: number;
            /** Downtime Reduction Minutes */
            downtime_reduction_minutes: number;
            /** Downtime Reduction Percent */
            downtime_reduction_percent: number;
            /** Optimized Asset Downtime Minutes */
            optimized_asset_downtime_minutes: number;
            /** Optimized Closure Minutes */
            optimized_closure_minutes: number;
            /** Rejected Maintenance Minutes */
            rejected_maintenance_minutes: number;
            /** Scheduled Maintenance Minutes */
            scheduled_maintenance_minutes: number;
        };
        /** LockRequest */
        LockRequest: {
            /** Job Id */
            job_id: string;
            /** Reason */
            reason: string;
        };
        /** LockResponse */
        LockResponse: {
            /** Job Id */
            job_id: string;
            /** Locked */
            locked: boolean;
            /** Reason Codes */
            reason_codes: string[];
            /** Run Id */
            run_id: string;
        };
        /** PlanningRunCreateRequest */
        PlanningRunCreateRequest: {
            /** Ruleset Version */
            ruleset_version: string;
            /** Snapshot Id */
            snapshot_id: string;
        };
        /** PlanningRunCreatedResponse */
        PlanningRunCreatedResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Ruleset Version */
            ruleset_version: string;
            /** Run Id */
            run_id: string;
            /** Snapshot Id */
            snapshot_id: string;
            state: components["schemas"]["PlanningRunState"];
            /** Status Url */
            status_url: string;
        };
        /** PlanningRunDetail */
        PlanningRunDetail: {
            /** Ai Estimates */
            ai_estimates: components["schemas"]["AiEstimate"][];
            approval?: components["schemas"]["ApprovalSummary"] | null;
            /** Changes */
            changes: {
                [key: string]: "SCHEDULED" | "REJECTED" | "PRESERVED" | "CHANGED";
            };
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Export Ready */
            export_ready: boolean;
            /** Jobs */
            jobs: components["schemas"]["JobContext"][];
            kpis: components["schemas"]["KpiSummary"];
            /** Parent Run Id */
            parent_run_id?: string | null;
            /** Ruleset Version */
            ruleset_version: string;
            /** Run Id */
            run_id: string;
            /** Schedule Items */
            schedule_items: components["schemas"]["ScheduleItem"][];
            /** Snapshot Id */
            snapshot_id: string;
            /** Snapshot Status */
            snapshot_status: string;
            state: components["schemas"]["PlanningRunState"];
            /** Unscheduled Jobs */
            unscheduled_jobs: components["schemas"]["UnscheduledJob"][];
            validator: components["schemas"]["ValidatorSummary"];
        };
        /**
         * PlanningRunState
         * @enum {string}
         */
        PlanningRunState: "QUEUED" | "RUNNING" | "FEASIBLE" | "OPTIMAL" | "INFEASIBLE" | "TIMEOUT" | "INVALID" | "FAILED";
        /**
         * PlanningRunSummary
         * @description Lightweight archive row for GET /planning-runs.
         *
         *     Deliberately excludes schedule_items/jobs/ai_estimates so listing the
         *     archive does not stream every job of every historical run.
         */
        PlanningRunSummary: {
            approval?: components["schemas"]["ApprovalSummary"] | null;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            kpis?: components["schemas"]["KpiSummary"] | null;
            /** Parent Run Id */
            parent_run_id?: string | null;
            /** Ruleset Version */
            ruleset_version: string;
            /** Run Id */
            run_id: string;
            /** Scheduled Job Count */
            scheduled_job_count: number;
            /** Snapshot Id */
            snapshot_id: string;
            state: components["schemas"]["PlanningRunState"];
            /** Total Job Count */
            total_job_count: number;
            /** Trigger Type */
            trigger_type: string;
            /** Validator Passed */
            validator_passed: boolean;
        };
        /** RapidBlockDetail */
        RapidBlockDetail: {
            /** Actor */
            actor: string;
            /** Actor Role */
            actor_role: string;
            /** Base Run Id */
            base_run_id: string;
            /** Base Snapshot Id */
            base_snapshot_id: string;
            candidate_plan_status?: components["schemas"]["PlanningRunState"] | null;
            /** Changed Jobs */
            changed_jobs: {
                [key: string]: "SCHEDULED" | "REJECTED" | "PRESERVED" | "CHANGED";
            };
            /** Child Run Id */
            child_run_id?: string | null;
            /** Derived Snapshot Id */
            derived_snapshot_id?: string | null;
            /** Justification */
            justification: string;
            /** Preserved Locked Jobs */
            preserved_locked_jobs: string[];
            /** Reason Codes */
            reason_codes: string[];
            /** Request Id */
            request_id: string;
            /**
             * Source Reported At
             * Format: date-time
             */
            source_reported_at: string;
            state: components["schemas"]["RapidBlockState"];
            /** Status Url */
            status_url: string;
            urgent_job: components["schemas"]["Job"];
            validator?: components["schemas"]["ValidatorSummary"] | null;
        };
        /** RapidBlockRequestCreate */
        RapidBlockRequestCreate: {
            /** Actor */
            actor: string;
            /**
             * Actor Role
             * @constant
             */
            actor_role: "PLANNER";
            /** Base Run Id */
            base_run_id: string;
            /** Justification */
            justification: string;
            /**
             * Source Reported At
             * Format: date-time
             */
            source_reported_at: string;
            urgent_job: components["schemas"]["Job"];
        };
        /** RapidBlockResponse */
        RapidBlockResponse: {
            /** Base Run Id */
            base_run_id: string;
            /** Base Snapshot Id */
            base_snapshot_id: string;
            /** Child Run Id */
            child_run_id?: string | null;
            /** Derived Snapshot Id */
            derived_snapshot_id?: string | null;
            /** Reason Codes */
            reason_codes: string[];
            /** Request Id */
            request_id: string;
            state: components["schemas"]["RapidBlockState"];
            /** Status Url */
            status_url: string;
        };
        /**
         * RapidBlockState
         * @enum {string}
         */
        RapidBlockState: "SUBMITTED" | "VALIDATING" | "REJECTED" | "PLANNING" | "CANDIDATE_READY" | "NO_CANDIDATE";
        /** ReplanRequest */
        ReplanRequest: {
            /** Affected Section Ids */
            affected_section_ids: string[];
            /** Affected Window Ids */
            affected_window_ids: string[];
        };
        /** ScheduleItem */
        ScheduleItem: {
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Job Id */
            job_id: string;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /** Reason Codes */
            reason_codes: string[];
            /**
             * Start
             * Format: date-time
             */
            start: string;
            status: components["schemas"]["ScheduleStatus"];
            /** Window Id */
            window_id: string;
        };
        /**
         * ScheduleStatus
         * @enum {string}
         */
        ScheduleStatus: "SCHEDULED" | "LOCKED" | "REJECTED";
        /** UnscheduledJob */
        UnscheduledJob: {
            /** Job Id */
            job_id: string;
            /** Reason Codes */
            reason_codes: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationIssue */
        ValidationIssue: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Field */
            field: string;
            /** Message */
            message: string;
            /** Row */
            row?: number | null;
        };
        /** ValidatorSummary */
        ValidatorSummary: {
            /** Issues */
            issues?: {
                [key: string]: unknown;
            }[];
            /** Passed */
            passed: boolean;
            /**
             * Validated At
             * Format: date-time
             */
            validated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    validate_dataset_endpoint_datasets_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetValidationResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_planning_runs_planning_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanningRunSummary"][];
                };
            };
        };
    };
    create_planning_run_planning_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanningRunCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanningRunCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_planning_run_planning_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanningRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_planning_runs__run_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_planning_runs__run_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lock_schedule_item_planning_runs__run_id__lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LockRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replan_planning_runs__run_id__replan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanningRunCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_railradar_trains__train_number__live_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                train_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_railradar_trains__train_number__route_get: {
        parameters: {
            query?: {
                format?: string;
                stops?: boolean;
            };
            header?: never;
            path: {
                train_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timetable_railradar_trains__train_number__timetable_get: {
        parameters: {
            query?: {
                halts_only?: boolean;
            };
            header?: never;
            path: {
                train_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rapidblock_request_rapidblock_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RapidBlockRequestCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RapidBlockResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rapidblock_request_rapidblock_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RapidBlockDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
